openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Sample API"
  description: "Initial example to submit Elasticsearch queries"

paths:
  /search:
    get:
      summary: "Submits a query to Elasticsearch"
      operationId: search
      tags:
        - search
      parameters:
        - name: query
          in: query
          description: "Query to be submitted"
          schema:
            type: string
        - name: page
          in: query
          description: "Page number"
          schema:
            type: integer
        - name: numResults
          in: query
          description: "Include the total number of results in the response"
          schema:
            type: boolean
            default: false
        - name: ordinationDate
          in: query
          description: "Use 0 for unsorted, 1 for ascending and 2 for descending"
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  numResults:
                    type: integer
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Result"
        500:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Result:
      type: object
      properties:
        title:
          type: string
        url:
          type: string
        abs:
          type: string
        date:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: "A human-readable error message"
          type: string
